services:
  - type: web
    runtime: docker
    name: shonenquiz-api
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
